### ISSUE TITLE
What are this libraries external dependencies?

### ISSUE THREAD

**Issue by smashedtoatoms** [brunato/xmlschema#1]
I am trying to use this in aws lambda because it appeared to be a pure python implementation; however, I can't import within lambda.  Are there dependencies on an underlying C library that I am not seeing?  If so, do you know what it is?

**Comment by smashedtoatoms** [comment]
Nevermind.  It looks fine because it is fine.  I added more memory to the lambda instance, and it works fine.  This library is great.  Thanks so much.

**Comment by brunato** [comment]
I confirm: the library has not external dependencies. Someone ask me to use lxml as optional dependency but the behaviour lxml library, at inner level, is a bit different from the xml.etree Python library (eg. string type, namespaces). In any case you can build a schema and then validate an XML document loaded using lxml etree.  I'm going to complete the library with a full XSD 1.0 coverage (the most is done but now lacks annotations and key references). Thank you for your appreciation.
