### ISSUE TITLE
Need to determine the base type of a complex element

### ISSUE THREAD

**Issue by virtuald** [brunato/xmlschema#10]
First off -- thank you, this library is awesome! 

I would like to be able to figure out what the base type of a complex element is, so I came up with this hack that monkeypatches an `extends_type` property onto XsdComplexType.

```
from xmlschema.components.xsdbase import get_xsd_attribute, get_xsd_component
from xmlschema.components.elements import XsdComplexType
from xmlschema.qnames import split_reference

def _extends_type(self):
    '''Hack on an 'extends_type' property to XsdComplexType'''
    if not self.has_extension():
        return None
    content_spec = get_xsd_component(self.content_type.elem)
    content_base = get_xsd_attribute(content_spec, 'base')
    base_qname, namespace = split_reference(content_base, self.schema.namespaces)
    return self.schema.maps.lookup_type(base_qname)

XsdComplexType.extends_type = property(fget=_extends_type)
```

Most of this logic is taken directly from factories.py ... seems to work, but not 100% sure of the best way this could be integrated into the existing library.

**Comment by brunato** [comment]
After a clash with circularity issues I decided to try the merge of factories code into `XsdComponent`'s subclasses. This can be done defining a __parse_ method, that is called whenever self.elem is set, each component is built once and with lesser complications. Also parsing errors can simply be collected by the component, raising at the end if the validation mode is 'strict'.

This could be the `_parse()` method for XsdUnion, that take the code of `xsd_union_factory()`:

```python
def _parse(self):
    elem = self.elem
    schema = self.schema
    options = self.options
    member_types = []

    for child in iter_xsd_declarations(elem):
        mt = xsd_simple_type_factory(child, schema, **options)
        if isinstance(mt, XMLSchemaParseError):
            self.errors.append(mt)
        else:
            member_types.append(mt)

    if 'memberTypes' in elem.attrib:
        for name in elem.attrib['memberTypes'].split():
            type_qname = split_reference(name, schema.namespaces)[0]
            mt = schema.maps.lookup_type(type_qname, **options)
            if isinstance(mt, XMLSchemaParseError):
                self.errors.append(mt)
            elif not isinstance(mt, XsdSimpleType):
                self.errors.append(XMLSchemaParseError("a simpleType required", mt))
            else:
                member_types.append(mt)

    if not member_types:
        self.errors.append(XMLSchemaParseError("missing union type declarations", self))

    self.member_types = member_types
```

Still some of work for this but I'm quite confident that's will be a good choice.
If you want to take a look at the development code I've pushed an 'altdev' branch into the repo.

In the development code I introduced also a XMLSchemaValidator base class (validator.py) for checking parsed components and schemas, that is based on XML Schema validation modes ('strict', 'lax', 'skip'). This ought resolve some validation options and define the library behaviour for each situation.

**Comment by brunato** [comment]
Factories code now is into class methods (version 0.9.10, just published). Seems to be a better choice for building and rebuilding XSD components. The components class hierarchy has been changed, in order to unify all XML Schema information items with the common base class `XsdBaseComponent` (module _xmlschema/xsdbase_).
In the same module the `XMLSchemaValidator` class has been replaced by a `ValidatorMixin`.

I wait observations about this or if you are satisfied please close the ticket.

Thanks

**Comment by virtuald** [comment]
I'll play with it at some point in the next week and get back to you.
