### ISSUE TITLE
Failed to handle spaces in xs:key xpath

### ISSUE THREAD

**Issue by hcw70** [brunato/xmlschema#105]
The following XSD gives an error message when parsed by xmlschema:

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="project" type="TProject">
        <xs:key name="widgetId">
            <xs:selector xpath=".//widgets/widget | .//logic/widget"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>

     <xs:complexType name="TProject">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="protocols"/>
        </xs:choice>
     </xs:complexType>

</xs:schema>

```

When removing the spaces around the xpath expression like this:
`            <xs:selector xpath=".//widgets/widget|.//logic/widget"/>
`
the xs:selector is accepted.

According to XSD spec https://www.w3.org/TR/xmlschema-1/#c-selector-xpath :

> For readability, whitespace may be used in selector XPath expressions even though not explicitly allowed by the grammar: whitespace may be freely added within patterns before or after any token. 

I am using xmlschema 1.10

Kind regards

Hauke

**Comment by brunato** [comment]
Hi,
this is not strictly related to *xmlschema* but to *elementpath* dependency. To verify this you should check if you are using the latest releases of *elementpath* (v1.1.6 or v1.1.7).

P.S.: In the next release of *xmlschema* I will include also a test for this with your sample schema.

Kind regards
Davide

**Comment by hcw70** [comment]
Thanks Davide for looking this up!
Actually i was using 1.1.5 of elementpath. Now i will try 1.1.7.

Kind regards
Hauke

**Comment by hcw70** [comment]
Unfortunately it still bails on that error when lusing elementpath 1.1.7

**Comment by brunato** [comment]
Maybe because also a modification on identities module was needed, a modification that I have forgotten that I've done.
Try if the new release v1.0.11 resolves this issue for you.

Thanks
