### ISSUE TITLE
Documentation request - Writing a new converter

### ISSUE THREAD

**Issue by saatvikshah1994** [brunato/xmlschema#109]
Thanks for this amazing library.

One use case I'm working on is to automatically generate SQL DML/DDL from XSD/XML using `xmlschema`. I already have a experimental implementation of SQL DDL setup. Next up while looking at implementing XML to SQL DML I came across the option to pass in a custom converter to `XMLSchema10`. Could you provide the basic requirements on writing a Converter(eg. I'm assuming `lossless`, etc properties need to be set) and methods/inputs we get access to when inheriting from `XMLSchemaConverter` that might be useful?

**Comment by brunato** [comment]
Hi,
I will extend the documentation for the next release adding a new section that describes available converters and the manner to implement your custom ones.

**Comment by brunato** [comment]
A new chapter on converters is available within the documentation of new release v1.0.13. Let me know if it's enough for learning how to build your custom converter.
Bye
