### ISSUE TITLE
choice + extensions not represented properly?

### ISSUE THREAD

**Issue by virtuald** [brunato/xmlschema#11]
So if I have...

```
  <xs:complexType name="base">
    <xs:sequence>
      <xs:element ... />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="child">
    <xs:complexContent>
      <xs:extension base="base">
        <xs:choice>
           ...
```

The current behavior adds the base elements directly to the XsdGroup in the child, which seems incorrect.

I would expect the child XsdComplexType.content_type to be an XsdGroup with a sequence model, that contains 2 elements, the single element from the base and an XsdGroup representing the choice element in the child.

I believe the issue is caused at https://github.com/brunato/xmlschema/blob/master/xmlschema/factories.py#L496

**Comment by brunato** [comment]
Please take a look at this issue with the new version 0.9.10.

**Comment by virtuald** [comment]
Will do.
