### ISSUE TITLE
An issue with an importing .xsd.

### ISSUE THREAD

**Issue by briankuehn** [brunato/xmlschema#110]
Hello!

Thanks for the excellent work with this package!

I am working on making a pre-system for a new Swedish tax form implementation, in python. I needed a schema-validater and stumbled upon your work. The problem seems to arise from the fact that there is an instance .xsd-file and a component .xsd-file. The instance file imports the component file. 

The problem I am running into is an element is fully qualified in the instance file as agd:avsandare, but is referenced as avsandare in the component file. The definition of the prefix "agd" is given in the instance file so I am not sure where the problem lies.

I am attaching the files I have used to cause the situation. They are all public files so there is no sensitive information being sent.

Thanks again for everything!

Brian Kuehn
Handen, Sweden

[Files for Swedish Tax Form.zip](https://github.com/brunato/xmlschema/files/3218740/Files.for.Swedish.Tax.Form.zip)

**Comment by briankuehn** [comment]
Hello again!

I've re-done the tests and now they are working. It was late last night. I'll have to attest to the fact that I was doing something wrong.

Sorry for the bother...

Brian

**Comment by brunato** [comment]
Don't worry (I saw, a wrong filename in a namespace import ...) this is another public schema and instance that I keep for my local collection of additional test cases.
Bye
Davide

**Comment by briankuehn** [comment]
Good that this will be of some help then!!

Brian

Skickat från min iPhone
