### ISSUE TITLE
RecursionError when calling XsdComplexType.is_derived on a redefined type

### ISSUE THREAD

**Issue by Treize44** [brunato/xmlschema#111]
Hello, 
I need to check if a XsdComplexType is a subtype of a base type.
Before 1.0.11 version, I used XsdComplexType.is_subtype().
Since 1.0.11 version, XsdComplexType.is_subtype() has disappeared and I use XsdComplexType.is_derived(). However, I get a RecursionError when the type is a redefinition.

**Comment by brunato** [comment]
Hi,
the version v1.0.11 implements complete checks on model restrictions, and the *is_subtype()* method has been dropped because is a duplication of *is_derived()*.
Could you provide a sample schema(s) for this?
Thanks

**Comment by Treize44** [comment]
First, thanks for your quick answer.

Here's my code :
Skeleton.xsd
`<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="blockDef" abstract="true">
		<xs:attribute name="isAttr1" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="extendedHeaderDef">
		<xs:complexContent>
			<xs:extension base="blockDef"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="optionalBlock">
		<xs:sequence>
			<xs:element name="extendedHeader" type="extendedHeaderDef"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
`
Impl.xsd:
`<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:redefine schemaLocation="Skeleton.xsd">
		<xs:complexType name="extendedHeaderDef">
			<xs:complexContent>
				<xs:extension base="extendedHeaderDef">
					<xs:attribute name="isAttr2" type="xs:boolean"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:redefine>
	<xs:element name="rootElement">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="block1" type="blockDef"/>
				<xs:element name="optional" type="optionalBlock"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
`
My Python code : 
`
import os
import xmlschema

xml_schema = xmlschema.XMLSchema('Impl.xsd', validation='skip')
extendedHeaderDef = xml_schema.types['extendedHeaderDef']
isEtensionFromBlockDef = extendedHeaderDef.is_derived(xml_schema.types['blockDef'])
print(isEtensionFromBlockDef)
`
I get : RecursionError: maximum recursion depth exceeded while calling a Python object
Thanks for your help

**Comment by brunato** [comment]
Fix available with release v1.0.13.
Bye

**Comment by Treize44** [comment]
Thanks ! It works fine.
