### ISSUE TITLE
traceback with nested xsd:include tags

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [brunato/xmlschema#12]
When I try to load the HL7 schemas (see below), I get a traceback; it seems to be related with nested xsd:include tags.

I know the schemas are valid because lxml.etree.XMLSchema - http://lxml.de/validation.html#xmlschema - manages to validate sample messages.

--------------------

How to test:
download all the xsd files from https://github.com/niquola/health_seven/tree/master/vendor/2.4

In [1]: import xmlschema                        

In [2]: xs = xmlschema.XMLSchema("messages.xsd")

The Traceback:

---------------------------------------------------------------------------
XMLSchemaKeyError                         Traceback (most recent call last)
<ipython-input-2-b8180d97fc9d> in <module>()
----> 1 xs = xmlschema.XMLSchema("messages.xsd")

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/schema.pyc in __init__(self, source, namespace, check_schema, global_maps, converter)
    153                 # the creator of the XSD globals maps.
    154                 if global_maps is None:
--> 155                     self.maps.build()
    156             else:
    157                 # If the META_SCHEMA is not instantiated do not import

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/namespaces.pyc in build(self)
    371         build_xsd_attribute_groups(self.attribute_groups, XSD_ATTRIBUTE_GROUP_TAG, **kwargs)
    372         load_xsd_complex_types(self.types, self.iter_schemas())
--> 373         build_xsd_complex_types(self.types, XSD_COMPLEX_TYPE_TAG, **kwargs)
    374         load_xsd_elements(self.elements, self.iter_schemas())
    375         build_xsd_elements(self.elements, XSD_ELEMENT_TAG, **kwargs)

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/namespaces.pyc in build_xsd_map(xsd_globals, tag, **kwargs)
    162                             continue
    163                         res_qname, xsd_instance = factory_function(
--> 164                             elem, schema, is_global=True, **kwargs
    165                         )
    166                     elif isinstance(obj, list):

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/factories.pyc in xsd_factory_wrapper(elem, schema, instance, is_global, **kwargs)
     48             try:
     49                 result = factory_function(
---> 50                     elem, schema, instance=instance, is_global=is_global, **kwargs
     51                 )
     52             except XMLSchemaValidationError as err:

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/factories.pyc in xsd_complex_type_factory(elem, schema, instance, **kwargs)
    527         content_base = get_xsd_attribute(content_spec, 'base')
    528         base_qname, namespace = split_reference(content_base, schema.namespaces)
--> 529         base_type = schema.maps.lookup_type(base_qname)
    530 
    531         derivation = content_spec.tag == XSD_EXTENSION_TAG

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/namespaces.pyc in lookup(global_maps, qname)
    118             obj = getattr(global_maps, map_name)[qname]
    119         except KeyError:
--> 120             raise XMLSchemaKeyError("missing a %s object for %r!" % (types_desc, qname))
    121         else:
    122             if isinstance(obj, xsd_classes):

XMLSchemaKeyError: "missing a XsdSimpleType or XsdComplexType object for u'{urn:com.sun:encoder}ID'!"

**Comment by brunato** [comment]
I just published a new version of the library that has important revisions on parsing the schemas, so the error message has a different format now.

I think the problem is related with imports of used namespaces.  Seems that those schemas lacks of explicit imports and the library cannot resolve external references. I have to resolve this adding an optional argument to the XMLSchema class in order to explicit imports other namespaces, but I've to think about it in order to choose a user friendly solution.

I don't know about sample messages validation that you refer, but also _lxml_ seems has some problems on building schema instances. I tried the latest version:

```
>>> from lxml import etree
>>> xt = etree.parse('messages.xsd')
>>> xs = etree.XMLSchema(xt.getroot())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/xmlschema.pxi", line 87, in lxml.etree.XMLSchema.__init__ (src/lxml/lxml.etree.c:196366)
lxml.etree.XMLSchemaParseError: complex type 'DFT_P03.CONTENT': The content model is not determinist., line 94
>>> xs = etree.XMLSchema(file='./messages.xsd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/xmlschema.pxi", line 87, in lxml.etree.XMLSchema.__init__ (src/lxml/lxml.etree.c:196366)
lxml.etree.XMLSchemaParseError: complex type 'DFT_P03.CONTENT': The content model is not determinist., line 94

```

**Comment by brunato** [comment]
I was wrong about imports. This was a problem related to incorrect simpleContent restriction. The 2.4 files seems to work in v0.9.11.

Anyway I have added a "build" argument to the schema constructor, so one can import many schemas and build the maps after, like the library do for the _meta_schema_ (schema.py 467-470)

``` python
meta_schema = _XMLSchema(meta_schema, build=False)
for uri, pathname in list(base_schemas.items()):
    meta_schema.import_schema(namespace=uri, location=pathname)
meta_schema.maps.build()
```
N.B. Another option is to build a _proxy schema_, in order to load required schemas.

The old schema methods `import_schemas`, `include_schemas` and `redefine_schemas` has been replaced by `import_schema` and `include_schema` that could be used to explicit imports/includes of other schemas.

**Comment by massimiliano-della-rovere** [comment]
Thank you for the fix for v.2.4!
I also need v.2.5 and 2.5.1.

v.2.5 fails:

In [1]: from xmlschema import XMLSchema

In [2]: XMLSchema("messages.xsd")      
---------------------------------------------------------------------------
XMLSchemaKeyError                         Traceback (most recent call last)
<ipython-input-2-760b3b88b67c> in <module>()
----> 1 XMLSchema("messages.xsd")

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/schema.pyc in __init__(self, source, namespace, validation, global_maps, converter, build)
    193 
    194             if build:
--> 195                 self.maps.build()
    196 
    197         def __repr__(self):

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/namespaces.pyc in build(self)
    358                             obj[k] = group_class(elem, schema, mixed=obj.mixed)
    359                         else:
--> 360                             obj[k] = element_class(elem, schema)
    361 
    362         # Rebuild substitution groups from element declarations

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/components/elements.pyc in __init__(self, elem, schema, name, is_global)
     56     """
     57     def __init__(self, elem, schema, name=None, is_global=False):
---> 58         super(XsdElement, self).__init__(elem, schema, name, is_global)
     59         if not hasattr(self, 'type'):
     60             raise XMLSchemaAttributeError("undefined 'type' attribute for %r." % self)

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/components/component.pyc in __init__(self, elem, schema, name, is_global)
     43         self.name = name
     44         self.schema = schema
---> 45         self.elem = elem
     46 
     47     def __setattr__(self, name, value):

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/components/elements.pyc in __setattr__(self, name, value)
     93                     etree_element(XSD_ATTRIBUTE_GROUP_TAG), schema=self.schema
     94                 )
---> 95         super(XsdElement, self).__setattr__(name, value)
     96 
     97     def _parse(self):

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/components/component.pyc in __setattr__(self, name, value)
     59                 self._elem = self.elem  # redefinition cases
     60             super(XsdComponent, self).__setattr__(name, value)
---> 61             self._parse()
     62             return
     63         elif name == "schema":

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/components/elements.pyc in _parse(self)
    134             elif 'type' in elem.attrib:
    135                 self._parse_error(msg % 'type', elem)
--> 136             xsd_element = self.maps.lookup_element(element_name)
    137             self.name = xsd_element.name
    138             self.type = xsd_element.type

/var/www/virtualenv/tcwa-27/lib/python2.7/site-packages/xmlschema/namespaces.pyc in lookup(qname)
    183                 obj = global_map[qname]
    184             except KeyError:
--> 185                 raise XMLSchemaKeyError("missing a %s object for %r!" % (types_desc, qname))
    186             else:
    187                 if isinstance(obj, xsd_classes):

XMLSchemaKeyError: "missing a XsdElement object for u'{urn:hl7-org:v2xml}ED'!"
