### ISSUE TITLE
Cannot import package if located in path with space

### ISSUE THREAD

**Issue by acGitUser** [brunato/xmlschema#17]
This is the traceback I have after a fresh install of xmlschema with pip:

PS C:\Users\NAME SURNAME> python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>>import xmlschema
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NAME SURNAME\Anaconda2\lib\site-packages\xmlschema\__init__.py", line 18, in <module>
    from .schema import XsdGlobals, XMLSchema
  File "C:\Users\NAME SURNAME\Anaconda2\lib\site-packages\xmlschema\schema.py", line 495, in <module>
    facets=XSD_FACETS
  File "C:\Users\NAME SURNAME\Anaconda2\lib\site-packages\xmlschema\schema.py", line 475, in create_validator
    meta_schema.import_schema(namespace=uri, location=pathname)
  File "C:\Users\NAME SURNAME\Anaconda2\lib\site-packages\xmlschema\schema.py", line 359, in import_schema
    reason="cannot import namespace %r: %s" % (namespace, err.reason)
xmlschema.exceptions.XMLSchemaURLError: <urlopen error cannot import namespace 'http://www.w3.org/2001/XMLSchema-hasFacetAndProperty': cannot access resource from 'C:\\Users\\NAME SURNAME\\Anaconda2\\lib\\site-packages\\xmlschema\\schemas
/XMLSchema-hasFacetAndProperty_minimal.xsd': [Error 2] Impossibile trovare il file specificato: u'C:\\Users\\NAME'; [Error 3] Impossibile trovare il percorso specificato: u'C:\\Users\\NAME SURNAME\\SURNAME\\Anaconda2\\lib\\site-packages
\\xmlschema\\schemas\\XMLSchema-hasFacetAndProperty_minimal.xsd'>

The problem seems the space in the base url "C:\Users\NAME SURNAME\", other installs without this space works perfectly.

**Comment by DuckHunter213** [comment]
I have the same error on python 3.6 in Visual Studio 

xmlschema.exceptions.XMLSchemaURLError: <urlopen error cannot import namespace 'http://www.w3.org/XML/1998/namespace': cannot access resource from 'C:\ProgramFiles\Python36\lib\site-packages\xmlschema\schemas/xml_minimal.xsd': [WinError 2] El sistema no puede encontrar el archivo especificado: 'C:\Program'; [WinError 3] El sistema no puede encontrar la ruta especificada: 'C:\Users\DARKE\source\repos\YellowTube\YellowTube\Files\Python36\lib\site-packages\xmlschema\schemas\xml_minimal.xsd'>

**Comment by DuckHunter213** [comment]
@acGitUser  A potential solution is changing the path of installation python to a new path, without spaces in blank

**Comment by brunato** [comment]
Fixed in the version 0.9.13. It was mainly an error into `resources.fetch_resource` function. This function was initially written for trying to fetch from a space separated list of URLs, than obviously cannot works with a file path containing spaces. 

So I've rewritten this function and adapted also the `fetch_schema` function with a for cycle. 
I close this issue, reopen if the problem persists.
