### ISSUE TITLE
imported refs are name-mangling keys and scheme.types is an empty dict

### ISSUE THREAD

**Issue by smashedtoatoms** [brunato/xmlschema#2]
When I convert my xml to a dict, I end up with keys like `'{http://xml.nbcuni.com/media/field}fpiv'`.  that url is the namespace, but I can't actually use that key.  When I run `schema.types`, it returns and empty dict.  It does validate the xml correctly though.  I have a schema with multiple imports.  I imagine I am doing something wrong.  And ideas?

**Comment by brunato** [comment]
I try to respond without a knowledge about your schema. 

The keys related to the namespace is a limitation that I have to resolve. I thought to replace the namespace with the prefix, so a users can manage it with namespace mapping from the XML document or from an optional argument.

The property schema.types is a view of global types, taken from the shared map schema.maps.types. Types defined in included schemas are listed in schema.types. Instead if you import a schema (a different namespace) the types of imported schema are not listed in schema.types but you can anyway find all declared types in schema.maps.types.

**Comment by brunato** [comment]
I've published an update of the package (v0.9.6) that should accomplish the mapping of namespace URIs to prefixes. The code try to extracts namespace information from the XML document that has to be decoded. In some cases this information is not yet available (in the case of you pass an ElementTree structure as the xml_document argument) so you cas pass an additional namespace argument for replacing URIs with prefixes.
