### ISSUE TITLE
Is there any plan to support parsing xml from memory instead of file

### ISSUE THREAD

**Issue by gaolizhou** [brunato/xmlschema#21]
It seems xmlschema can only parsing xml by passing xml file name. But in many cases, parsing xml string is also needed.
 
So is there any plan to support this?

Thanks!

**Comment by brunato** [comment]
Strings are already accepted for schemas (the 'source' argument), not for XML documents. 

It was in the initial plans to support strings also for _xml_document_ argument, but I had found difficulties on writing reliable resource access internal methods. Now those internal methods are mature so I could retry. 

Meanwhile one can use StringIO for creating a file-like object from a string.

**Comment by gaolizhou** [comment]
Thanks for your quick reply! Let me try with SttringIO

**Comment by brunato** [comment]
I've tried again the decode api (to_dict) passing XML as a string and I've verified that XML decoding already works also passing XML as a string (see also the issue #22 for an example). 

Which is the method that doesn't work for you about passing XML as a string?

P.S.: `StringIO` is a resource of the python library that you can use to simulate a file-like resource strarting from a string, useful when an API accepts only files. See the [official documentation](https://docs.python.org/3.6/library/io.html) about this module.
