### ISSUE TITLE
Option to make to_dict to consistent with using arrays for sequences defined by xsd

### ISSUE THREAD

**Issue by ruffsl** [brunato/xmlschema#22]
First, this is a great library, making it so much easier to work with xsd and xml files!

One thing I noticed is that the [`to_dict`](https://github.com/brunato/xmlschema/blob/678d7a07002b33bbdbb66dc43097e14a44d35d54/xmlschema/xsdbase.py#L292) function is not consistent in how it creates values in the dictionary for sequences. The sequence can already be anticipated from the .xsd, so I would have expected those values to be within array structures no matter the number of sequence elements present in the parent xml element.

A minimal example showing this inconsistency:

xsd_string =
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xs:element name="foo" type="Foo" />

    <xs:complexType name="Foo">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="bar" type="Bar" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Bar">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="subject_name" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
</xs:schema>
``` 

xml_string_1 = 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<foo>
    <bar name="bar_1">
        <subject_name>Bar #1</subject_name>
    </bar>
</foo>
```

xml_string_2 = 
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<foo>
    <bar name="bar_1">
        <subject_name>Bar #1</subject_name>
    </bar>
    <bar name="bar_2">
        <subject_name>Bar #2</subject_name>
    </bar>
</foo>
```

``` python
>>> import xmlschema
>>> xsd_schema = xmlschema.XMLSchema(xsd_string)
>>> xml_data_1 = xsd_schema.to_dict(xml_string_1)
>>> xml_data_2 = xsd_schema.to_dict(xml_string_2)
>>> xml_data_1
{'bar': {'@name': 'bar_1', 'subject_name': 'Bar #1'}}
>>> xml_data_2
{'bar': [{'@name': 'bar_1', 'subject_name': 'Bar #1'},
  {'@name': 'bar_2', 'subject_name': 'Bar #2'}]}
```

Note the value for bar is either a `list` or `dict` depending on the xml elements, regardless of xsd.

**Comment by joefromct** [comment]
So, based on your example above, it looks like `xml_data_1` should have `bar` as a _list_ of length 1 (including a dictionary) rather than a dictionary on it's own.  I think that is reasonable and was my assumption also.  

In the past I've switched from `xmltodict` to this `xmlschema` for this very reason... thinking the xsd would give us this better insight into exactly what type of data structure we should be looking at.

FYI, this problem was discussed for `xmldict` [here](https://github.com/martinblech/xmltodict/issues/14)...  I believe however `xmltodict` doesn't really have an opportunity for a fix as they have no input xsd to work with (or validated against).  Seems there is hope with xmlschema. 

-Joe

**Comment by brunato** [comment]
From the version 0.9.9 this package includes _converters_, so one could define his own custom conversion (take a look at brunato/xmlschema#3).

For this issue I looked at the code of the current version and I've found a typo/bug in `converters.py` at line 137 into a test to determine if create a list or not for a child element:

This condition:
```python
if xsd_child is not None and xsd_child.is_single():
```
ought to be changed to:
```python
if xsd_child.is_single() and xsd_element.type.content_type.is_single():
```
(the safety test `xsd_child is not None` is not needed anymore ...).

With this modification the code will produce a list in both cases:
```python
>>> xsd_schema.to_dict(xml_string_1)
{'bar': [{u'@name': u'bar_1', 'subject_name': u'Bar #1'}]}
>>> xsd_schema.to_dict(xml_string_2)
{'bar': [{u'@name': u'bar_1', 'subject_name': u'Bar #1'}, {u'@name': u'bar_2', 'subject_name': u'Bar #2'}]}
```

P.S.: A `force_list` option maybe inserted but for my opinion maybe better in a custom coverter that doesn't use schema's information.

Waiting for your feebacks about that.
Thanks

**Comment by joefromct** [comment]
Thanks brunato for all your help. 

> From the version 0.9.9 this package includes converters, so one could define his own custom conversion (take a look at brunato/xmlschema#3).

This sounds good, I suspect converters are the way to go.  
_(I only linked to the other python library as they were thinking through the same problem.... a problem that sounds solved with the typo/bug fix below. )_


> For this issue I looked at the code of the current version and I've found a typo/bug in converters.py at line 137 into a test to determine if create a list or not for a child element:

Do you know if version 0.9.9 has this fix in it?  

-Joe

**Comment by brunato** [comment]
Not in any version, I've changed the line in my develop, but if needed I will push a new release on pip (0.9.14) ASAP.

**Comment by ruffsl** [comment]
What should I be expecting if the xsd permitted a minOccurs of 0 for the xs:sequence in Foo xs:complexType, but then xml document it happens that the foo element is void of any bar children?

``` xml
...
    <xs:complexType name="Foo">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="bar" type="Bar" />
        </xs:sequence>
    </xs:complexType>
...
```

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<foo>
</foo>
```
I would expect to receive an empty list `[]` , correct?

**Comment by brunato** [comment]
With an empty content the _xmlschema_ default converter simply produce `None`:
```python
>>> xml_string_3 = """<?xml version="1.0" encoding="UTF-8"?>
... <foo>
... </foo>
... """
>>> xs.to_dict(xml_string_3)  # None
```
A `None` value would be a convention when an emptiable element is empty (both `simpleType` and `complexType`). On the issue brunato/xmlschema#4 the user refers to the JSON spec. 
With the BadgerFish convention the result for 'foo' is an empty dict:
```
>>> xs.to_dict(xml_string_3, converter=xmlschema.BadgerFishConverter, dict_class=dict)
{'foo': {}}
```

**Comment by brunato** [comment]
The new version 0.9.14 of the package is available on PyPI.
Bye
Davide
