### ISSUE TITLE
Decimal('x.y') not a good type

### ISSUE THREAD

**Issue by arsphl** [brunato/xmlschema#27]
In builtins.py line 265 you use Decimal as a type to replace decimal.

{
        'name': xsd_qname('decimal'),
        'python_type': Decimal,
        'facets': (DECIMAL_FACETS, COLLAPSE_WHITE_SPACE_ELEMENT)
    },  # decimal number

In python 3.5 (I did not check with others) Decimal('x.y')  would return when evaluated Decimal('x.y') instead to x.y

Can I suggest that you use float there also ?
{
        'name': xsd_qname('decimal'),
        'python_type': float,
        'facets': (DECIMAL_FACETS, COLLAPSE_WHITE_SPACE_ELEMENT)
    },  # decimal number

Otherwise I can't use your library, It breaks Json serialisation.

Cheers,

Philippe

**Comment by brunato** [comment]
The Decimal type is the best match if you want to validate an encoded or decoded datum. Float has the drawback of aproximation and someone could prefer to use a string. 

So for data conversion, and particularly for JSON, the _xmlschema_ decode API already includes an _decimat_type_ optional argument that you can use as decimal_type=float:

  http://xmlschema.readthedocs.io/en/latest/api.html#schema-level-api

Try it and give me a feedback if it works.
Thanks
Davide
