### ISSUE TITLE
XML Schema support for MinOccurs and MaxOccurs

### ISSUE THREAD

**Issue by davlee1972** [brunato/xmlschema#3]
This is a great package. I tried a ton of other ones before stumbling on this one.

One thing I've noticed is that the to_dict() function doesn't behave consistently when MinOccurs > 1 or MaxOccurs > 1  or unbounded.

The bikes.xsd says there can be 0 to many bikes in the XML file.

        <xs:element name="bike" type="vh:vehicleType"
          minOccurs="0" maxOccurs="unbounded" />

If you look at the dictionary results:

The first test case creates vh:bike as an array of dictionaries with 2 bikes which is correct.
'vh:bikes': {'vh:bike': [{'make': 'Harley-Davidson', 'model': 'WL'}, {'make': 'Yamaha', 'model': 'XS650'}]}

The second test case creates vh:bike as just a dictionary with 1 bike which is not consistent
'vh:bikes': {'vh:bike': {'make': 'Harley-Davidson', 'model': 'WL'}}

Shouldn't the second test case create vh:bike as an array of dictionaries with just one dictionary in the array?
'vh:bikes': {'vh:bike': [{'make': 'Harley-Davidson', 'model': 'WL'}]}

The reasoning behind this is that in some XML files you would could only see one item, but in others it could be many, but the Python dictionary object is not consistent between the two cases.

Test Case:

Copy vehicles.xml to vehicles2.xml.
Remove Yamaha from the bikes section.

        import xmlschema
        my_schema = xmlschema.XMLSchema("vehicles.xsd")
        a = my_schema.to_dict("vehicles.xml")
        a
        {'vh:bikes': {'vh:bike': [{'make': 'Harley-Davidson', 'model': 'WL'}, {'make': 'Yamaha', 'model': 'XS650'}]}, 'xsi:schemaLocation': 'http://example.com/vehicles vehicles.xsd', 'vh:cars': {'vh:car': [{'make': 'Porsche', 'model': '911'}, {'make': 'Porsche', 'model': '911'}]}}
        a = my_schema.to_dict("vehicles2.xml")
        a
        {'vh:bikes': {'vh:bike': {'make': 'Harley-Davidson', 'model': 'WL'}}, 'xsi:schemaLocation': 'http://example.com/vehicles vehicles.xsd', 'vh:cars': {'vh:car': [{'make': 'Porsche', 'model': '911'}, {'make': 'Porsche', 'model': '911'}]}}

**Comment by brunato** [comment]
This behaviour is wanted because when there are more occurrences of a tag a list is necessary to define an order and to distinguish them. In case of only one occurrence the list container is not necessary, then it can be omitted. This is like the JSON encoding/decoding behaviour or the processing made by of another packages/functions that translate an XML to a dictionary.

Thank you

**Comment by davlee1972** [comment]
All the other packages out there convert XML to JSON without a XSD, so there is no way of knowing whether a tag could be a list of one. They are all basically guessing, by sampling a XML file and applying fuzzy logic. However with an XSD you have both data types and cardinality defined. When dealing with hundreds of XML files let's say like orders for vehicles, it would be possible for some files to contain zero, one or many bikes. This is a show stopper when working with big data products like Apache Drill and Apache Parquet. Drill cannot parse JSON records if one nested key is a dictionary and the same key in another record is a nested list. Parquet which is a nested columnar format has the same problem if data is not represented consistently.

**Comment by davlee1972** [comment]
A side question. Let's say there is an element which is called account and the XSD says it is type XS:string. In one XML file the XML contains <account>abcxyz</account> while a second contains <account>123456</account>. Will this package convert both into Python strings? All the other packages out there also fail this use case by converting 123456 to a it instead of '123456'. Using an XSD to validate XML is important, but not using the XSD to convert XML to dictionaries or JSON leads to unexpected results.

**Comment by davlee1972** [comment]
This issue is summarized also in this post..
https://tapadoo.com/2011/regular-problem-with-xml-to-json-converters/

**Comment by davlee1972** [comment]
Sample python code which bombs when dictionary definitions differ between file even when both use the same XML schema

>>> import xmlschema
>>>
>>> my_schema = xmlschema.XMLSchema('vehicles.xsd')
>>>
>>> vehicles = my_schema.to_dict('vehicles.xml')
>>>
>>> for i in vehicles['{http://example.com/vehicles}bikes']['{http://example.com/vehicles}bike']:
...     print(i["make"])
...
Harley-Davidson
Yamaha

>>> vehicles = my_schema.to_dict('vehicles2.xml')
>>>
>>> for i in vehicles['{http://example.com/vehicles}bikes']['{http://example.com/vehicles}bike']:
...     print(i["make"])
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: string indices must be integers
>>>

So when writing a python program which processes hundreds of different XML files conforming to the same schema you run into problems if the python dictionary is not consistent between files.

**Comment by brunato** [comment]
Okay, I will consider this issue in decoding/encoding for the next version. I know that this theme isn't simple and suggestions like your can help to do the better choices. Anyway the decoder know exaclty the maxOccurs value and can optate beetween a list (with one or more values) or a single value. Probably I will inserting a kwarg option for this with default of no collapsing when maxOccurs > 1.

**Comment by davlee1972** [comment]
Thanks. That will help a lot.. I found another quirk after doing some hacks to converting single items to lists of one item. Optional attributes create dictionaries mixed in with arrays.

        <xs:complexType name="YEAR_ATTR_STRING_75">
                <xs:simpleContent>
                        <xs:extension base="STRING_75">
                                <xs:attribute name="Year" type="xs:integer" use="optional"/>
                        </xs:extension>
                </xs:simpleContent>
        </xs:complexType>

Examples output from different files:

{Certificates': {'CertificationName': ['CFA']}}
{Certificates': {'CertificationName': [{'Year': 1991, '_text': 'CFA'}]}}
{Certificates': {'CertificationName': ['CPA', {'Year': 1990, '_text': 'CFA'}]}}
{Certificates': {'CertificationName': ['CPA']}}
{Certificates': {'CertificationName': ['CPA', 'CFA']}}

Python code would iterate though these lists expecting dictionaries, but the ones without the optional Year would end up being just strings.

Adding some hacks to convert this to:

{Certificates': [{'CertificationName': 'CFA'}]}
{Certificates': [{'Year': 1991,'CertificationName': 'CFA'}]}
{Certificates': [{'CertificationName': 'CPA'}, {'Year': 1990, 'CertificationName': 'CFA'}]}
{Certificates': [{'CertificationName': 'CPA'}}}
{Certificates': [{'CertificationName': 'CPA', 'CertificationName': 'CFA']}

This is a bit complex. Need to check if apply a child's maxOccurs="unbounded" to the parent if there are no other children for that parent.

**Comment by davlee1972** [comment]
I took a look at the package and didn't see an easy way to fix this when generating the objects so I wrote some functions to apply fixes to the final dictionary.

1. Added the xml root element to the dictionary
2. In cases where min_occurs > 1, max_occurs >1 or max_occurs = "unbounded" then make sure the dictionary key's value is a list. Convert the key's value to a list with one entry if it isn't a list.
Example: [{'a': '123'}, {'a : ['123','456']}]  is converted to  [{'a': ['123']}, {'a': ['123','456']}] 
3. In cases where there are optional attributes make sure the key's value is a dictionary. Convert the key's value to a dictionary of {'_text': value} if it isn't a dictionary.
Example: [{'a': '123'}, {'a': {'_text': '123', '_id': 1}}]  is converted to  [{'a': {'_text' = '123'}}, {'a': {'_text': '123', '_id': 1}}]

Working on unwrapping all element attributes
{'z': '789', 'a': {'_text': '123', '_id': 1}} would look cleaner if it was converted to {'z': '789', 'a': '123',
  'a_id': 1}

`

    my_schema = xmlschema.XMLSchema(xsd_file)

    dict_array_set = set()
    dict_optional_set = set()

    def xmlSchema_dict(obj, elem_xpath):
        attrib_list = obj.findall('@*')
        for attrib in attrib_list:
            if obj.get_attribute(attrib).is_optional():
                dict_optional_set.add(elem_xpath)

        obj_list = obj.findall('*')
        for i in range(len(obj_list)):
            if obj_list[i].max_occurs is None or obj_list[i].min_occurs > 1 or obj_list[i].max_occurs > 1:
                dict_array_set.add(elem_xpath + '/' + obj_list[i].name)

            xmlSchema_dict(obj_list[i], elem_xpath + '/' + obj_list[i].name)

    xmlSchema_dict(my_schema, '')

    def fixDict(obj, elem_xpath):
        for k, v in obj.items():
            # Set empty dictionaries to None
            if isinstance(v, dict):
                if len(v) == 0:
                    obj[k] = None
                else:
                    #Apply logic to child dictionaries in the dictionary
                    fixDict(obj[k], elem_xpath + '/' + k)
            elif isinstance(v, list):
                for idx in range(len(v)):
                    #Apply logic to child dictionaries in the list
                    if isinstance(v[idx], dict):
                        if len(v[idx]) == 0:
                            obj[k][idx] = None
                        else:
                            #Apply logic to child dictionaries in the dictionary
                            fixDict(obj[k][idx], elem_xpath + '/' + k)

            # Turn objects into a wrapped object if there are use="optional" attributes
            if elem_xpath + '/' + k in dict_optional_set and not isinstance(obj[k], dict):
                if isinstance(obj[k], list):
                    for idx in range(len(obj[k])):
                        if not isinstance(obj[k][idx], dict):
                            obj[k][idx] = {'_text': obj[k][idx]}
                else:
                    obj[k] = {'_text': obj[k]}

            # Turn single objects into a list with one object if maxOccurs="unbounded", etc.
            if elem_xpath + '/' + k in dict_array_set and not isinstance(obj[k], list):
                obj[k] = [obj[k]]
`

**Comment by brunato** [comment]
I've thought about this problem. The structure you might want is similar to a tree structure (like ElementTree) instead to a dictionary. The to_dict has different objective (path to objects-elements, interfacing to JSON) and that probably can't fit into what you need.

Maybe better considering another solution with a different method. One option to evaluate is decorating an Element tree structure with decoded values or decoder methods.

A common problem is to avoid name collisions between tag and attribute names, solution that generally is implement with a prefix for the attributes (`@`). This is what I've added in the version 0.9.7 (optional arguments text_key="#text" for the text part of a complex content and attribute_prefix='@' for the attributes).

Thanks

**Comment by davlee1972** [comment]
Couple of additional comment and ideas:

http://wiki.open311.org/JSON_and_XML_Conversion has some naming conventions for elements and attributes

I'm not sure if there is a clean workaround with creating something like result_list in the package..

I posted my working python script to the repo below:
https://github.com/davlee1972/xml_to_json

python xml_to_json.py -p XPATH -x XSD_FILE -l test.log -v file1.xml file2.xml other_files*.xml

The script above has a couple tweaks and features.

A. Uses iterparse to break up giant XML files (5+ gigs) by creating smaller XML strings, converting them to dictionaries > JSON and then periodically writing JSON strings out to a JSON file.
B. Adds multiprocessing to concurrently convert 10 XML files at once if you have hundreds of XML files sitting in some directory. If you have under a 100 files it will convert files starting with the largest XML file first.
C. Extends the XMLSchema class as follows:

Captures Xpaths for elements and attributes which have the following characteristics.
    my_schema.dict_array_set = set() #min_occurs > 1, max_occurs > 1 or max_occurs = "unbounded"
    my_schema.dict_optional_set = set() #elements with attributes which have use = "optional"
    my_schema.dict_simple_set = set() #elements which are simple content
    my_schema.dict_single_set = set() #elements which are dictionaries which only contain a single key
    my_schema.dict_attribute_set = set() #elements which have attributse

Two of the tweaks are required to create consistent JSON strings which I'm then converting to Apache Parquet files using Drill. If varA is a string for one element and varA is a list for another element Apache Drill and other tools will complain that a schema change has occurred and error out.
https://drill.apache.org/docs/troubleshooting/#schema-changes

The end result is an Apache Parquet file which contains JSON objects which is only 7% the size of the original JSON file. https://drill.apache.org/docs/querying-complex-data-introduction/

Required Tweak #1 - Convert single elements to an array with one item if the element is in my_schema.dict_array_set

Required Tweak #2 - Convert single elements to an dictionary with one key if the element is in my_schema.dict_optional_set

Optional Tweaks applied after Required Tweaks:
Rename all attributes to parent element.tag + @ + attribute.name instead of @ + attribute_name
Rename all element text to element.tag instead of #text
Unwrap nested dictionaries which are simple content. 
{"b: {"a":{"@Id":123, "#text":"hello"}}} becomes {"b: {"a@Id":123, "a":"hello"}}
Unwrap nested dictionaries which are lists of simple content with no other elements in the complex time
{"CertificationName":[{"#text":"CPA"},{"#text":"CFA"}]} becomes [{"CertificationName":"CPA"},{"CertificationName":"CFA"}]

D. After adding @ to attribute names it looks like find and findall using @Id* as a search string no longer works. Only exact match like @Id works.

**Comment by brunato** [comment]
Thought a lot about the XLM to JSON decoding conventions: for the new release (0.9.9) the `iter_decode` methods will be improved and into the method ` XsdElement.iter_decode()` a customizable function will be inserted to format the decoded data, considering also the schema of the XSD element. The optional arguments "dict_class", "force_list", "text_key" and "attribute_prefix" will be replaced by one argument "element_hook" (or "element_decode_hook") that shall be used to change the decode format.
 
The use of `iterparse ()` for decoding big files will be considered after.

**Comment by brunato** [comment]
Published the 0.9.9 version. Takes a look at the new module `converters.py`. The decoding process is now customized at element level using converter objects. Those objects compose decoded data (content and attributes), maps XML namespaces and building the data structure of the desired format. A generic converter is the base class and other subclasses implement various XML to JSON conventions (only decode for now).

**Comment by brunato** [comment]
You have to consider that the converter/decoding process could change a little, because now I'm developing the encoding of a data structure to an ElementTree. So the scripts based on the published version may need to be changed for working with a next release.

I close the ticket for now. 

Thank you for suggestions.

**Comment by davlee1972** [comment]
The default XMLSchemaConverter is returning back an error:

'str' object has no attribute 'get'

I tried the BadgerFish converter and it worked fine.

**Comment by davlee1972** [comment]
Created my own converter as well and tested it.

Avoids @ and $ and other special characters.
Forces elements with attributes defined in the XSD into dictionary types even if the attributes are not present in the XML.
Unwraps nested dictionaries by prefixing nested attributes with element.tag
Unwraps nested lists which are simple content lists


> class ParqConverter(xmlschema.XMLSchemaConverter):
    """
    XML Schema based converter class for Parquet friendly json.
    :param namespaces: Map from namespace prefixes to URI.
    :param dict_class: Dictionary class to use for decoded data. Default is `OrderedDict`.
    :param list_class: List class to use for decoded data. Default is `list`.
    :param element_class: Element class to use when encode data to an ElementTree \
    structure. Default is `xml.etree.ElementTree.Element`.
    """
    def __init__(self, namespaces=None, dict_class=None, list_class=None, element_class=None):
        super(ParqConverter, self).__init__(
            namespaces, dict_class or OrderedDict, list_class, element_class,
            attr_prefix=None, content_key=None, cdata_prefix=None
        )

    def map_attributes(self, tag, attributes):
        """
        Creates an iterator for converting decoded attributes to a data structure with
        appropriate prefixes. If the instance has a not-empty map of namespaces registers
        the mapped URIs and prefixes.
        :param attributes: A sequence or an iterator of couples with the name of \
        the attribute and the decoded value. Default is `None` (for `simpleType` \
        elements, that don't have attributes).
        """
        if not attributes:
            return
        else:
            for name, value in attributes:
                yield u'%s%s' % (tag, self.map_qname(name)), value

    def element_decode(self, elem, xsd_element, content, attributes=None):

        if hasattr(xsd_element.type, 'attributes'):
            result_dict = self.dict([(k, v) for k, v in self.map_attributes(elem.tag, attributes)])
        else:
            result_dict = self.dict()

        if xsd_element.type.is_simple():
            result_dict[elem.tag] = content
        else:
            for name, value, xsd_child in self.map_content(content):
                if value:
                    if xsd_child.is_single():
                        if xsd_child.type.is_simple():
                            for k in value.keys():
                                result_dict[k] = value[k]
                        else:
                            result_dict[name] = value
                    else:
                        if xsd_child.type.is_simple() and len(xsd_element.findall("*")) == 1:
                            try:
                                result_dict.append(value)
                            except AttributeError:
                                result_dict = self.list([value])
                        else:
                            try:
                                result_dict[name].append(value)
                            except KeyError:
                                result_dict[name] = self.list([value])
                            except AttributeError:
                                result_dict[name] = self.list([value])

        return result_dict
