### ISSUE TITLE
[Question] Using XML schema to find and enable substitution of missing elements?

### ISSUE THREAD

**Issue by ruffsl** [brunato/xmlschema#30]
I've been working on a simple pre-processor for auto generating valid xml documents or expanding them from partially valid XML document as a sudo-templates. The goal here being that users could provide a function a xsd schema, a partially valid xml document and a default xml document containing any missing elements within it's flat root default namespace.

I have a semi working example of what I'd like to do documented here:
https://gist.github.com/ruffsl/251d10ec2a815e0d6c9c5a8002ba3036

Currently it suffers from some strange behaviors, most likely a combination of my misuse of iterators or difficulties with satisfying `xs:sequence`'s. I've tried simplifying my schema group requirements from `sequence` to `all`, but ran up against issue https://github.com/brunato/xmlschema/issues/28 . I thought about just limiting the default pre-processor to operate on empty sequences to avoid the need for correctly sorting the inserted substituted elements to satisfy sequence order, but encountered issue:   https://github.com/brunato/xmlschema/issues/29 .

Eventually though, I'd like to support sequences, as most of the other schema I'm working with depend on that type of grouping. So I'd like to ask if there would be any way of ascertaining from the yealded chunks from `iter_decode` iterator what the expected index was, so that a substituted default could be correctly interred. Additionally, if you see anything airy with the iterators, cause the infinite loops or duplicate substitutions, that would also be helpful.

Hope the recent ticketed issues have been helpful.
Related: https://stackoverflow.com/questions/18694988/xsd-default-value-of-a-missing-element

**Comment by joefromct** [comment]
This sounds pretty interesting, I've been thinking about trying to hack something simlar together using [the faker module](https://github.com/joke2k/faker) for performance testing of many xml documents (after i have my valid xsd).

**Comment by ruffsl** [comment]
In particular, my intended use case for this capability is for staging configuration information in a (certificate) build system. Users would outline specific settings via a simplified template, such as only the certificate subject name (as in my linked example), then relay on a separate default file to provide the missing required context as per the XSD. This allows user template files themselves to remain agnostic build time specific settings, such as period-of-validity or issuer-certificate-authority, thus succinctly containing only the most relevant information.

I've approached this build configuration ideas before using yaml files, as the self referencing syntax was useful in balancing succinct nested formats with element overriding. But being able to formalize the configuration format using XSD schema greatly simplifies interpretation, as the app can validate the data, providing the build logic some format integrity guarantees, as well clear file description for others' to interface into.

However with XML, I still missed having a good method for parameter substation given customization to the global build context, like users could structure with in yaml, but I didn't want to have to re-write any fallback logic into the interpreter given the fragility should the XSD ever need modification. So that was why I found programmatically substituting any omitted elements via prepossessing with the schema appealing.

**Comment by ruffsl** [comment]
Its working a bit better now https://gist.github.com/ruffsl/251d10ec2a815e0d6c9c5a8002ba3036

I looked over the `XsdElement` class some more and recognized the the context for the expected index I needed to expose, as seen in this sample PR https://github.com/brunato/xmlschema/pull/31 . 

I also recognized that some of the internal yealding functions where iterating on the dynamic length of the element, so I had to change my looping strategy to return after each new substitution. Its not as efficient, as it ends up looping over the front end of the document more than necessary, but it behaves predictably.

Still having an issue with https://github.com/brunato/xmlschema/issues/29 , so I'm not able to predicatively initialize empty complex types an depend on consecutive iterations to recursively populate it.

**Comment by ruffsl** [comment]
I've updated my gist to reflect the fixes with #28 and #29 : 
https://gist.github.com/ruffsl/251d10ec2a815e0d6c9c5a8002ba3036

Thanks to those patches, I can more easily populate missing elements recursively. I've also updated my sample PR #31 I rely on in the gist, as I still need a way to ascertain the original context of the new `XMLSchemaChildrenValidationError`'s, specifically the index and expected element tag.

**Comment by ruffsl** [comment]
Updated my example with xmlschema v0.9.18 that now includes:


All is well. Thanks @brunato !

**Comment by ruffsl** [comment]
I've updated my gist to reflect v1.0.1:
https://gist.github.com/ruffsl/251d10ec2a815e0d6c9c5a8002ba3036

But I was getting some strange errors with using the same ElementTree.Element types as before. For instance, without this change here, to ensure `missing_elem` is what ever special form of Element that chunk.elem is:

``` diff
-                        missing_elem = ElementTree.Element(expected)
+                        missing_elem = chunk.elem.__class__(expected)
```

I get this nonsensical type error:

``` python
No default found!
     chunk.reason:  The content of element 'authority' is not complete. Tag 'cert' expected.
     index:  0
     expected:  cert
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-fee4f77e354e> in <module>()
----> 1 xml_data_2B = preprocess_default(xsd_schema, data=xml_string_3, default_data=xml_string_default_b)
      2 print_xml(xml_data_2B)

<ipython-input-21-2a192852e5a4> in preprocess_default(xsd_schema, data, default_data, path, use_defaults)
     13             use_defaults)
     14 
---> 15         for missing_error in iter_errors:
     16             missing_errors.append(missing_error)
     17 #             raise missing_error

<ipython-input-21-2a192852e5a4> in default_preprocessor(xsd_schema, xml_document, xml_document_default, path, use_defaults)
     55                         print('    ', 'index: ', index)
     56                         print('    ', 'expected: ', expected)
---> 57                         chunk.elem.insert(index, missing_elem)
     58                         yield chunk
     59                         return

TypeError: insert() argument 2 must be xml.etree.ElementTree.Element, not Element
```
@brunato , would you know how the classes have changed here that prevent the strait use of `xml.etree.ElementTree.Element`?

**Comment by brunato** [comment]
Hi,

in version 1.0+ I've introduced `XMLResource` class in order to manage XML various type of sources (file path, element tree, string, url) in a class. But it shouldn't have an impact on previous usage with default arguments.
 
It's necessary to debug your code script to understand which Element is exactly generated and passed to your script (eg. lxml.etree.Element).

Davide

**Comment by ruffsl** [comment]
> It's necessary to debug your code script to understand which Element is exactly generated and passed to your script (eg. lxml.etree.Element).

How would you propose this? I'm not seeing a difference in the self reported object types from the two different class constructors.

**Comment by brunato** [comment]
Found something: for some reasons Jupyter uses the Element Python implementation instead of the accellerated C implementation.

```python
$ python
Python 3.6.6 (default, Jul 19 2018, 14:25:17) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xml.etree import ElementTree
>>> print(dir(ElementTree.Element))
['__class__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'attrib', 'clear', 'extend', 'find', 'findall', 'findtext', 'get', 'getchildren', 'getiterator', 'insert', 'items', 'iter', 'iterfind', 'itertext', 'keys', 'makeelement', 'remove', 'set', 'tag', 'tail', 'text']
>>> print(dir(ElementTree._Element_Py))
['__bool__', '__class__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_assert_is_element', 'append', 'attrib', 'clear', 'copy', 'extend', 'find', 'findall', 'findtext', 'get', 'getchildren', 'getiterator', 'insert', 'items', 'iter', 'iterfind', 'itertext', 'keys', 'makeelement', 'remove', 'set', 'tag', 'tail', 'text']
```
xmlschema uses the C accelerated version (Element), jupyter import (ElementTree.Element) is the Python implementation, not the accelerated C version.

**Comment by ruffsl** [comment]
> Found something: for some reasons Jupyter uses the Element Python implementation instead of the accellerated C implementation.

I'm not sure that is the case here. If you test out the imports carefully,  you'll see that the import of `ElementTree.Element` is the Python implementation only if `xmlschema` is imported before hand, regardless of Jupiter or iPython. This leads me to believe that the importation of `xmlschema` is missing with the global environment to cause this.

### Without xmlschema
```
$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xml.etree import ElementTree
>>> print(dir(ElementTree.Element))
['__class__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'attrib', 'clear', 'extend', 'find', 'findall', 'findtext', 'get', 'getchildren', 'getiterator', 'insert', 'items', 'iter', 'iterfind', 'itertext', 'keys', 'makeelement', 'remove', 'set', 'tag', 'tail', 'text']
>>> exit()
```

### With xmlschema before
```
$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlschema
>>> print(xmlschema.__version__)
1.0.2
>>> from xml.etree import ElementTree
>>> print(dir(ElementTree.Element))
['__bool__', '__class__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_assert_is_element', 'append', 'attrib', 'clear', 'copy', 'extend', 'find', 'findall', 'findtext', 'get', 'getchildren', 'getiterator', 'insert', 'items', 'iter', 'iterfind', 'itertext', 'keys', 'makeelement', 'remove', 'set', 'tag', 'tail', 'text']
>>> exit()
```

### With xmlschema after
```
$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xml.etree import ElementTree
>>> print(dir(ElementTree.Element))
['__class__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'attrib', 'clear', 'extend', 'find', 'findall', 'findtext', 'get', 'getchildren', 'getiterator', 'insert', 'items', 'iter', 'iterfind', 'itertext', 'keys', 'makeelement', 'remove', 'set', 'tag', 'tail', 'text']
>>> import xmlschema
>>> print(xmlschema.__version__)
1.0.2
>>> print(dir(ElementTree.Element))
['__class__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'attrib', 'clear', 'extend', 'find', 'findall', 'findtext', 'get', 'getchildren', 'getiterator', 'insert', 'items', 'iter', 'iterfind', 'itertext', 'keys', 'makeelement', 'remove', 'set', 'tag', 'tail', 'text']
>>> exit()
```

**Comment by brunato** [comment]
There is a probably workaround for this problem in the version v1.0.4. The problem is related to *defusedxml* import. See issue #80 for further information.
