### ISSUE TITLE
Memory usage issue

### ISSUE THREAD

**Issue by yrunts** [brunato/xmlschema#32]
After importing xmlschema memory usage is increased to more than 200MiB.

Requirements (tested with python 2.7 and python 3.5):
```
pip install xmlschema
pip install memory-profiler
```

Create script test.py:
```
@profile
def my_func():
    import xmlschema
    return 2

if __name__ == '__main__':
    my_func()
```
Run: python -m memory_profiler test.py
Results:
```
Line #    Mem usage    Increment   Line Contents
     2   10.762 MiB   10.762 MiB   @profile
     3                             def my_func():
     4  233.723 MiB  222.961 MiB       import xmlschema
     5  233.723 MiB    0.000 MiB       return 2
```

@brunato  I haven't investigated issue too deep yet. Do you have any ideas why library needs so much RAM? Any ideas where to start digging?

**Comment by brunato** [comment]
The package needs to build Unicode categories to parse XML Schema's regular expressions. Take a look at `codepoints.py`. Without them the regexp validation maybe unpracticable. The best solution should be to build a C module for that. 

Another source of RAM consumption can be the XSD metaschema (`xmlschema.XMLSchema.META_SCHEMA`), but should be significatively less than codepoints.

**Comment by yrunts** [comment]
Thanks. You are right. After loading categories from 'unicode_categories.json' memory usage is increased on ~100Mb. Building categories['C'] leads to additional consumption of 40Mb. So dict UNICODE_CATEGORIES consumes ~140Mb of ram. It is dict with 2228224 ints. It is really huge overload especially in multiprocessed applications.

**Comment by brunato** [comment]
I agree, but currently is the best that I can do for keep XML regex validation working. Probably the best solution is a reworking of the Python's C module, adding a call for get a representation of the unicode categories.
Thanks

**Comment by brunato** [comment]
I wrote a new version of the class `UnicodeSubset` that resolves the
memory issue. Now `UnicodeSubset` uses an ordered-list to store the code
points, instead of a _set()_ instance. Many overrides of `MutableSet`'s
methods were needed to reach good performances.

Seems pretty memory-efficient now:

```bash
$ python -m memory_profiler test_xmlschema_memory.py
Filename: test_xmlschema_memory.py

Line #    Mem usage    Increment   Line Contents
================================================
     1   14.625 MiB   14.625 MiB   @profile
     2                             def my_func():
     3   24.574 MiB    9.949 MiB       import xmlschema
     4   28.062 MiB    3.488 MiB       import lxml.etree
     5   28.781 MiB    0.719 MiB       import unicodedata
     6   28.781 MiB    0.000 MiB       return 2
```

The codepoints module, including all Unicode categories, now uses less
than 0.7 MiB.

**Comment by brunato** [comment]
You can found the new code in the master branch or in the version 0.9.16 on PyPI.
Please try the new version and tell me if I you consider this issue resolved.

**Comment by yrunts** [comment]
Thanks for update.

```
Python 2.7.12 (default, Jan 16 2017, 11:42:38)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlschema
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/__init__.py", line 18, in <module>
    from .validators.exceptions import (
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/validators/__init__.py", line 19, in <module>
    from .attributes import XsdAttribute, XsdAnyAttribute, XsdAttributeGroup
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/validators/attributes.py", line 26, in <module>
    from .simple_types import XsdSimpleType
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/validators/simple_types.py", line 31, in <module>
    from .facets import (
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/validators/facets.py", line 25, in <module>
    from ..regex import get_python_regex
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/regex.py", line 20, in <module>
    from .codepoints import UNICODE_CATEGORIES, UNICODE_BLOCKS, UnicodeSubset
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/codepoints.py", line 573, in <module>
    UNICODE_CATEGORIES = get_unicode_categories()
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/codepoints.py", line 570, in get_unicode_categories
    return {k: UnicodeSubset(v) for k, v in categories.items()}
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/codepoints.py", line 570, in <dictcomp>
    return {k: UnicodeSubset(v) for k, v in categories.items()}
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/codepoints.py", line 192, in __init__
    self.update(args[0])
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/codepoints.py", line 291, in update
    self.add(cp)
  File "/Users/yr/.virtualenvs/test/lib/python2.7/site-packages/xmlschema/codepoints.py", line 296, in add
    raise XMLSchemaValueError("not a Unicode code point range: %r" % value)
TypeError: not all arguments converted during string formatting
```

**Comment by brunato** [comment]
Is related to Python 2.7 configure option:

`--enable-unicode[=ucs[24]]    Enable Unicode strings (default is ucs2)`

It seems ucs4 is generally selected for distro compiled version of Python 2.7, but from the source it compiles with ucs2 for default.

```python
$ /usr/local/bin/python2.7
Python 2.7.13 (default, Dec 26 2017, 12:27:34) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys      
>>> sys.maxunicode
65535

$ /usr/bin/python2.7
Python 2.7.14 (default, Nov  2 2017, 18:42:05) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.maxunicode
1114111
```

I'll insert a pair of checks of `maxunicode` value in `codepoints.py` in order to use JSON file and codes > 65536 only if UCS-4 is enabled.

**Comment by yrunts** [comment]
great job, thanks
