### ISSUE TITLE
Validate report invalid file as valid

### ISSUE THREAD

**Issue by gregoire-avot** [brunato/xmlschema#35]
Hi,

In sequence item in XML, subnodes not described is XSD are not always detected.
XML example:
<tns:specifications>
  ...
  <tns:xxx>4</tns:xxx>   ( xxx not part of specification sequence in XSD))
  ...
</tnd:specifications>

It seems to me this non-detection problem occurs if all elements in sequence are optional, of if element appear after mandatory element, and only for 2+ level in XSD.

I can share XSD + XML if you want/need to fix it.

Best regards,

Grégoire.

**Comment by brunato** [comment]
Yes, If you share the XSD schema and XML file I can try to fix it. Also highlight the part of the schema that cause the issue. 

Thanks
Davide

**Comment by smiglidigli** [comment]
[dates.zip](https://github.com/brunato/xmlschema/files/1643196/dates.zip)
Have the same problem. files attached.

**Comment by brunato** [comment]
The new version 0.9.20 should resolves this issue. Some modifications to `iter_decode()` and `iter_decode_children()` of XsdGroup and XsdAnyElement classes were needed. 

Now the validator checks if there is a residual content not examined by the model (_iter_decode_children_), and in this case generates an error and performs a raw decoding of the residual content:
 
https://github.com/brunato/xmlschema/blob/781ac12cbbbf6445dd059dff4600bc89ffb7fc54/xmlschema/validators/groups.py#L331-L356
