### ISSUE TITLE
Enhancement Request: JSON Schema

### ISSUE THREAD

**Issue by davlee1972** [brunato/xmlschema#48]
Would it be possible to create a function  to generate a valid JSON Schema using the XSD?

http://json-schema.org/examples.html
https://stackoverflow.com/questions/3922026/generate-json-schema-from-xml-schema-xsd

I ran into a problem with the JSON files below. The XSD says zip is a xs:string, but because one of the XML files didn't have any zip values the entire JSON file ends up with "zip":null.

There is no way to figure out what type of data is "zip" in b.json as a result..

    a.json:
    { "city":"San Francisco", "zip":"94105"}
    { "city":"San Jose", "zip":"94088"}
    
    b.json:
    { "city":"Toronto ", "zip": null}
    { "city":"Montreal", "zip" null}

**Comment by brunato** [comment]
At the moment there is not interest for JSON Schema in the scientific group that I work with.
 
In any case this could be an argument for dependant package that use an `XSDSchema` instance for generating code, not for this library. As an example of a similar case I'm going to work soon to a code that uses xmlschema and jinja2 templates to generate Fortran source code, but the generator code will go into another package, not in this library.

An XML Schema expert has recently published an [XQuery script](https://gist.github.com/lcahlander/0eecf499dfe307d7aecbb15f775bd4f2 ) that produces a JSON Schema from an XSD file. You could try to use this script to find out if it can resolve your needs.

Best regards
Davide
