### ISSUE TITLE
xmlschema not reporting validation issue

### ISSUE THREAD

**Issue by gregpinero** [brunato/xmlschema#50]
Validating in oxygen I get this validation issue:
Description: cvc-id.1: There is no ID/IDREF binding for IDREF 'P0'.

But running the same xsd and xml documents in xmlschema it returns an emtpy list and passes everything.

**Comment by brunato** [comment]
Hello,
If you provide references to XSD schema and XML docs that generate this validation issue with Oxygen, I shall check the same parts with _xmlschema_ library.

Best Regards
Davide

**Comment by brunato** [comment]
Closed until more information will be furnished about the issue.
