### ISSUE TITLE
empty separator returned for string

### ISSUE THREAD

**Issue by davlee1972** [brunato/xmlschema#7]
This element is returning back empty sepatator..

`<LegalType _Id="FO">FO</LegalType>`

Starting on line 24 in attributes.py

Not sure how this would ever work.. spilt('') on a string shouldn't be possible..

def get_attributes(obj):
    if isinstance(obj, dict):
        return obj
    elif isinstance(obj, str):
        return {(attr.split('=', maxsplit=1) for attr in obj.split(''))}
    else:
        return obj.attrib

**Comment by brunato** [comment]
This was a typo. Thank you for reporting it. 

Anyway I removed this function from the latest version, because the library will uses only the dictionary format, passing the `elem.attrib.`
