### ISSUE TITLE
Encoding with namespaces is confusing

### ISSUE THREAD

**Issue by pythonator** [brunato/xmlschema#70]
Hello,
Ideally, running `to_dict` and then `encode` would return the exact same xml file. I found it hard to get this to work when I had namespaces in the XML file. Perhaps I am missing something?

Ideally, this would work:
```python
import xmlschema
import xml.etree

XSD_PATH = r"C:\Miniconda3\Lib\site-packages\xmlschema\tests\cases\examples\collection\collection.xsd"
XML_PATH = r"C:\Miniconda3\Lib\site-packages\xmlschema\tests\cases\examples\collection\collection.xml"
OUT_XML_PATH = r'C:\tmp\out_collection.xml'

xsd = xmlschema.XMLSchema(XSD_PATH)
xsd.validate(XML_PATH)
d = xsd.to_dict(XML_PATH)
new_etree = xsd.elements['collection'].encode(d)
new_xml_text = xml.etree.ElementTree.tostring(new_etree).decode('utf8')
print(new_xml_text)
import time; time.sleep(0.01)  # Separate stdout and stderr in PyCharm
with open(OUT_XML_PATH, 'w') as f:
    f.write(new_xml_text)
xsd.validate(OUT_XML_PATH)
```

To get the `xsd.validate(OUT_XML_PATH)` to pass, I needed to use the following code:
```python
import xmlschema
import xml.etree

XSD_PATH = r"C:\Miniconda3\Lib\site-packages\xmlschema\tests\cases\examples\collection\collection.xsd"
XML_PATH = r"C:\Miniconda3\Lib\site-packages\xmlschema\tests\cases\examples\collection\collection.xml"
OUT_XML_PATH = r'C:\tmp\out_collection.xml'

xsd = xmlschema.XMLSchema(XSD_PATH)
xsd.validate(XML_PATH)
d = xsd.to_dict(XML_PATH)

# Without the following code, encode raises:
# xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating dict_items([('xsi:schemaLocation', 'http://example.com/ns/collection collection.xsd')]) with XsdAttributeGroup().
# Reason: 'xsi:schemaLocation' attribute not allowed for element.
for bad_attr in ('@xsi:schemaLocation', '@xsi:noNamespaceSchemaLocation'):
    if bad_attr in d:
        del d[bad_attr]

# new_etree = xsd.encode(d, 'col:collection', namespaces={'col': 'http://example.com/ns/collection'})
new_etree = xsd.elements['collection'].encode(d)

# Without the following two lines, the output contains
# <ns0:collection xmlns:ns0="http://example.com/ns/collection">
# Which then causes validation to fail.
new_etree.tag = 'col:collection'
new_etree.set('xmlns:col', "http://example.com/ns/collection")

new_xml_text = xml.etree.ElementTree.tostring(new_etree).decode('utf8')
print(new_xml_text)
import time; time.sleep(0.01)  # Separate stdout and stderr in PyCharm
with open(OUT_XML_PATH, 'w') as f:
    f.write(new_xml_text)
xsd.validate(OUT_XML_PATH)
```

Even with all the tweaks I did, I couldn't get the output to be identical to the input:
The input:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<col:collection xmlns:col="http://example.com/ns/collection"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://example.com/ns/collection collection.xsd">
	...
</col:collection>
```
The output:
```xml
<col:collection xmlns:col="http://example.com/ns/collection">
    ...
</col:collection>
```

**Comment by brunato** [comment]
The namespace mapping to and from dictionary data depends by conversion convention (eg. Badgerfish) and by the etree library used. I would like to support both `xml.etree` and `lxml.etree` for XML data and this implies the manage some different behaviours of the lxml library.

Some improvements to `XMLSchemaConverter` class, that I hope would resolve namespace mapping, will be included in the next release. For ensure this the XML tests cases will include equality tests for XML data after a decode and encode.

You can then verify this problem after the release of the new version.

**Comment by brunato** [comment]
The namespace mapping is enhanced in version 1.0.1. Namespaces are mapped also into the decoded objects. 
Please try if it works better for this and in case close this issue or reply with another comment.

**Comment by brunato** [comment]
I close this issue, considering it resolved. Try also the new version 1.0.2 published today, and reopen the issue if you have any update about this.

**Comment by brunato** [comment]
Ok, I'll consider your observation for next versions of the library. Reserved prefixes `n0`, `n1`,... are associated when not registered namespaces are used. Namespace-prefix can change document by document and this make preservation of the original a little bit difficult.

So your analysis should be correct. Only one question: are you using the last version of the library (1.0.3)?

Thanks

**Comment by pythonator** [comment]
Yes, I was using 1.0.3 (the master branch they day I answered).
Thanks for your help!
