### ISSUE TITLE
Consistent return type for 'lax' validation in `to_dict`

### ISSUE THREAD

**Issue by giovannipizzi** [brunato/xmlschema#72]
in https://github.com/brunato/xmlschema/blob/7bddce0449e2c0104faa92c56fd8d365c8b4702f/xmlschema/validators/xsdbase.py#L546
the return type is either a tuple `(dictionary, errors)` if there are errors, or just the `dictionary` if there are no errors, if the validation is `lax`. This is quite complex to catch in a calling code.
Could you just always return a tuple in the case of `lax`, possibly containing an empty list of errors? This would simplify a lot the logic when calling `to_dict`.

**Comment by brunato** [comment]
Seems reasonable. Anyway if one use 'lax' validation the he/she is already expecting a tuple or a dictionary.

_**If this proposal will not receive any opposite opinion this change will be applied from next release.**_

**Comment by brunato** [comment]
Published the release 1.0.2 that implements this proposal both for *decode/to_dict* and *encode/to_etree*.  Try the new package and, if it's conforming to what proposed, close this issue.
