### ISSUE TITLE
Can't parse document without namespace

### ISSUE THREAD

**Issue by gdetrez** [brunato/xmlschema#77]
I'm not sure if this is an issue or if I just didn't find the proper way to use the library.

I would like to parse XML documents for which I have an XSD schema. Some document have an `xmlns` attribute in the root tag and I can use `to_dict` without issue:
```xml
<?xml version="1.0" encoding="utf-8"?>
<foo xmlns="http://example.com/foo">bar</foo>
```
```python
>>> schema.to_dict('./foo.xml') 
'bar'
```

Other however come without the `xmlns` attribute:
```xml
<?xml version="1.0" encoding="utf-8"?>
<foo>bar</foo>
```
I thought I would be able to parse those anyway by passing `namespaces` to `to_dict` but that doesn't seem to be the case:

```python
>>> schema.to_dict('./foo-noxmlns.xml', namespaces={'': 'http://example.com/foo'})
[...]
Reason: 'foo' is not a global element of the schema!

Instance:

  <foo>bar</foo>
```
I also tried to give the namespaced tag name as `path` but I get a different error:

```python
>>> schema.to_dict('./foo-noxmlns.xml', path='{http://example.com/foo}foo', namespaces={'': 'http://example.com/foo'})
[...]
ElementPathSyntaxError: unexpected symbol '{' at line 1, column 1.
```
Finally, I tried passing `validation='skip'` but then `to_dict` just returns `None`.

**Comment by brunato** [comment]
Hi, which version do you use?

**Comment by gdetrez** [comment]
I use 1.0.3 from pypi with python 3

**Comment by brunato** [comment]
Those XML examples are different. In the first the nemespace of _foo_ is `http://example.com/foo`, in the second _foo_ has no namespace (not only the prefix, also the namespace). You can verify it also using the `xml.etree.ElementTree` library:

```python 
>>> import xml.etree.ElementTree as et
>>> print(et.fromstring("""<foo xmlns="http://example.com/foo">bar</foo>"""))
>>> print(et.fromstring("""<foo >bar</foo>"""))
<Element '{http://example.com/foo}foo' at 0x7fad2f0b4208>
<Element 'foo' at 0x7fad2f0b4390>
```

Passing a path you cannot resolve it, because in the second XML the default namespace is empty, not `http://example.com/foo`. The last error is due to a wrong XPath syntax (only prefixed form are admitted in XPath expressions so you can pass `path='foo'` and `namespaces={'': 'http://example.com/foo'}` to find `{http://example.com/foo}foo`, but it's still useless in the second XML where _foo_ has no namespace.

**Comment by gdetrez** [comment]
Hi, thanks for your quick answer!
I understand the example are different, but I assumed that passing in `namespaces` would allow me to use `xmlschema` with my namespace-less document. But maybe I didn't understand the role of the `namespaces` argument?

I did a bit of digging and I think the problem may come from `XMLSchema.find()`. Here is the result of some quick tests in the python repl:
```py
>>> schema.find('{http://example.com/foo}foo')                            #1
XsdElement(name='foo', occurs=[1, 1])
>>> schema.find('foo')                                                    #2
# None
>>> schema.find('bar:foo', namespaces={'bar': 'http://example.com/foo'})  #3
XsdElement(name='foo', occurs=[1, 1])
>>> schema.find('foo', namespaces={'': 'http://example.com/foo'})         #4
# None
```
The last case (`#4`) is of particular interest because I think this is what is happening in `iter_decode` when I do ` schema.to_dict('./foo-noxmlns.xml', namespaces={'': 'http://example.com/foo'})`.
I would have expected it to be equivalent to the one just above, `#3` with `bar:foo`. But again maybe I don't quite understand the namespace concept.

Here's my test schema, in case it matters:

```xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="http://example.com/foo"
  targetNamespace="http://example.com/foo"
  elementFormDefault="qualified">

  <xsd:element name="foo" type="xsd:string"></xsd:element>

</xsd:schema>
```

**Comment by brunato** [comment]
`XMLSchema.find()` uses an XPath API of the _elementpath_ package. May be a problem or a limitation that I've to check in that package. In case of a bug on processing the default namespace I will publish a new release for the _elementpath_ package.

**Comment by brunato** [comment]
The problem with the default namespace has been fixed with the release 1.0.12 of the _elementpath_ library. Now the n. 4 example works as expected:

```python
>>> schema.find('foo', namespaces={'': 'http://example.com/foo'})
XsdElement(name=u'foo', occurs=[1, 1])
```
Also another default namespace related bug has been fixed in the xmlschema library, and will be available with the next release.

About your initial question: XPath cannot ignore the namespace difference, but namespace wildcard can also be applied:

```python
>>> schema.to_dict('<foo>bar</foo>', path='/foo', namespaces={'': 'http://example.com/foo'})
>>> schema.to_dict('<foo>bar</foo>', path='/*:foo', namespaces={'': 'http://example.com/foo'})
u'bar'
```

**Comment by brunato** [comment]
`elementpath>=1.0.12` is now also a requirement of the release 1.0.4 of *xmlschema*.

**Comment by Sidekickcomical** [comment]
It’s clear now https://pythondev.space/questions/utilizing-etree-in-python-to-work-with-xpath-expressions-and-namespaces-featuring-prefixes
