### ISSUE TITLE
XMLSchemaParseError: XSD 1.0 do not allows 'ALL' group extensions

### ISSUE THREAD

**Issue by vovkanych** [brunato/xmlschema#78]
> XMLSchemaParseError: XSD 1.0 do not allows 'ALL' group extensions:
> 
> Schema:
> 
> <Element '{http://www.w3.org/2001/XMLSchema}extension' at 0x7fe1acf3eb38>

I have an error running xmlschema.XMLSchema(). Have you seen such an error, any ideas?
Can't put here the xsd due to privacy reasons.
Thank you,
Bests,
Ivan

**Comment by brunato** [comment]
Your schema contains a `complexType` extension with the base type that has an "ALL" model group as content type. This content model extension is not allowed for XSD 1.0 schemas.

So probably your xsd is an XSD 1.1 schema, a version that is not supported yet by this library (my estimation is for 3-4 months of work for a first version containing XSD 1.1 support).

All the best,
Davide

**Comment by vovkanych** [comment]
Thank you for your reply,

It looks like an xsd version 1.0:
"
```
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
  <xsd:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="schema_w3.org.2000.09.xmldsig.xsd"/>
```
"

**Comment by brunato** [comment]
Hi,
if you refer to the _XML declaration_:
```xml
<?xml version="1.0" encoding="UTF-8"?>
```
it's not related to the XSD version but to XML version (that is still at 1.0).

The XSD version can be related to attributes declared within the namespace "http://www.w3.org/2007/XMLSchema-versioning" that are not mandatory.

Best Regards,
Davide

**Comment by vovkanych** [comment]
Davide,
thank you for clarification,
Best Regards,
Ivan
