### ISSUE TITLE
Pattern restrictions for special characters in XPATH expressions not working as intended

### ISSUE THREAD

**Issue by ikrEErki** [brunato/xmlschema#79]
If you have a pattern restriction for an attribute, if the pattern contains special characters like new line (\n) or tab (\t), this lib escapes the "\\", making the pattern wrong.

Look at this schema:
`<xs:schema>
	<xs:element name="root">
		<xs:complexType>
			<xs:attribute name="test">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[^\n\t]+"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>`

The following XML should be valid according to the schema but is not:
`<root test="abcnt"></root>`

This must be because the xmlschema library converts the xpath "[^\n\t]+" to "[^\\\n\\\t]+". The result is a pattern that does not allow "\\", "n" or "t" instead of not allowing "\n" and "\t" (new line and tab).

Is this something that could be fixed? 

Best regards,
ikrEErki

**Comment by ikrEErki** [comment]
Awesome, thanks! 

Btw, thanks for a great library. I've been missing proper XSD support for python for a long time and just recently found this lib.

Best,
ikrEErki

**Comment by brunato** [comment]
Issue fixed into new release 1.0.4.
