### ISSUE TITLE
How to remove targetnamespace

### ISSUE THREAD

**Issue by davlee1972** [brunato/xmlschema#84]
I just updated my ParquetConverter to 1.05..

How do I remove the targetnamespace from the root element?
I added a bunch of map_qname() calls to remove them from attributes and elements.
Basically if my root element is called "myroot", the JSON output has something that starts with:

`{"{http://schemas.dummy.com/2012/06/30/version20}myroot":`

How do I remove the http namespace from the json?

```
class ParqConverter(xmlschema.XMLSchemaConverter):
    """
    XML Schema based converter class for Parquet friendly json.
    """

    def __init__(self, namespaces=None, dict_class=None, list_class=None, **kwargs):
        kwargs.update(attr_prefix='', text_key=None, cdata_prefix=None)
        super(ParqConverter, self).__init__(
            namespaces, dict_class or ordered_dict_class, list_class, **kwargs
        )

    def __setattr__(self, name, value):
        if name in ('text_key', 'cdata_prefix') and value is not None:
            raise XMLSchemaValueError('Wrong value %r for the attribute %r of a %r.' % (value, name, type(self)))
        super(xmlschema.XMLSchemaConverter, self).__setattr__(name, value)

    @property
    def lossless(self):
        return False

    def element_decode(self, data, xsd_element, level=0):
        """
        :param data: Decoded ElementData from an Element node.
        :param xsd_element: The `XsdElement` associated to decoded the data.
        :return: A dictionary-based data structure containing the decoded data.
        """
        map_qname = self.map_qname

        if data.attributes:
            self.attr_prefix = map_qname(data.tag)
            result_dict = self.dict([(k, v) for k, v in self.map_attributes(data.attributes)])
        else:
            result_dict = self.dict()

        if xsd_element.type.is_simple() or xsd_element.type.has_simple_content():
            result_dict[map_qname(data.tag)] = data.text if data.text is not None and data.text != "" else None

        if data.content:
            for name, value, xsd_child in self.map_content(data.content):
                if value:
                    if xsd_child.is_single():
                        if xsd_child.type.is_simple() or xsd_child.type.has_simple_content():
                            for k in value:
                                result_dict[k] = value[k]
                        else:
                            result_dict[name] = value
                    else:
                        if (xsd_child.type.is_simple() or xsd_child.type.has_simple_content()) and len(xsd_element.findall("*")) == 1:
                            try:
                                result_dict.append(value)
                            except AttributeError:
                                result_dict = self.list([value])
                        else:
                            try:
                                result_dict[name].append(value)
                            except KeyError:
                                result_dict[name] = self.list([value])
                            except AttributeError:
                                result_dict[name] = self.list([value])

        return result_dict

```

**Comment by brunato** [comment]
Usually in the JSON format the namespace URI is mapped to prefix. I don't know about your XML source, but you need a map from namespace to prefix (also an empty prefix). 

Have you tryed passing `namespaces={'': 'http://schemas.dummy.com/2012/06/30/version20'}`?

**Comment by davlee1972** [comment]
Ok that worked..
I had to pass in both namespaces and process_namespaces to to_dict().
I thought process_namespaces=True would have worked on its own..

`my_dict = my_schema.to_dict(root, namespaces = my_schema.namespaces, process_namespaces=True)`

Next question.. Maybe an enhancement..

I'm using iterparse() to work with really large XML files in the Gigabytes so reading the entire file into memory isn't an option..

`context = ET.iterparse(xml_file, events=("start", "end"))`

Is there a way to call to_dict() on a path..

Basically if my xml is:

<parent>
   <child></child>
   <child></child>
   <child></child>
</parent>

as I'm running through iterparse() 

I want to get <child> and convert child to a dictionary and then to json. Write the json to a file and process the next <child>

to_dict() takes (xml, path) where the xml is the entire xml document and path is a xpath in that doc

Can it take (xml, xpath) where xml is valid xml (child) for a xpath (/parent/child)?

Right now I'm jury rigging the XML by doing a:
parent_path.append(child_elem)
to_dict(root, path = "/parent/child")
parent_path.remove(child_elem)

**Comment by davlee1972** [comment]
Hacky parent append parent remove logic here:

https://github.com/davlee1972/xml_to_json/blob/633fe21ff6a7fcf46e2cba77809f76eb73cebe2c/xml_to_json/convert_xml_to_json.py#L172-L174

**Comment by brunato** [comment]
Hi,
as I understand you need something of very specific. Should be interesting to examine for the future also for xmlschema.

I considered the problem of *iterparse* in the XMLResource, but it's only an idea still not completely developed yet. My actual priority is to complete the XSD 1.1 implementation and to consolidate the current features of the package.

Best Regards
Davide
