### ISSUE TITLE
way of finding built-in types

### ISSUE THREAD

**Issue by miaozn** [brunato/xmlschema#9]
XSD as an example:
```xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="root"/>
  <xs:complexType name="root">
      <xs:element name="empno" type="xs:string"/>
      <xs:element name="age" type="xs:unsignedByte" />
  </xs:complexType>
</xs:schema>
```
Looks like that "xs:string" and "xs:unsignedByte" are not stored in class XsdAtomicBuiltin.
After building the schema by the following code:
```python
xs = xmlschema.XMLSchema('xsd')
```
Now I need traverse the schema tree and when I get to the XsdAtomicBuiltin node, looks like I have no way to get the "type" info.

**Comment by brunato** [comment]
The schema is wrong (an xs:element cannot be a direct child of xs:complexType) but indicate a real problem about the schema validity. 

In a recent version I've rewritten the schema parser, in a mode that collects all schema errors and put replacements for failed elements (whenever possible), but I forgot to raise an error at the end of schema building (see `xs.errors` that is not empty for you case), mainly because I was undecided about how to manage cases where the schema is partially built (built with errrors). 

Now I've decided to replace "validate/check_schema" arguments with an only one "validation" argument, that has the meaning of XSD validation modes ('strict', 'lax', 'skip'). Will be fixed for the next release (0.9.10).

**Comment by miaozn** [comment]
Is the schema wrong ? In this case, what should be the correct one? Thanks.

**Comment by miaozn** [comment]
This one correct?
```xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="root"/>
  <xs:complexType name="root">
    <xs:sequence>
      <xs:element name="empno" type="xs:string"/>
      <xs:element name="age" type="xs:unsignedByte" />
    <xs:sequence>
  </xs:complexType>
</xs:schema>
```

Anyway, my question is bout about the validation.. I am building a tool and I need traverse the xsd tree using your data structures. When I get to the XsdAtomicBuiltin nodes (the "empno" and "age"), is there a way to retrieve the type of them (string and unsignedByte) ? Thanks.

**Comment by brunato** [comment]
Yes, this a correct schema.

For the second question. The XsdAtomicBuiltin objects are XSD built-in types for simple elements, and could be used as bases for defining other types (global or local). 

You elements ("empno" and "age") have a type attribute, that point to global types of the XML Schema namespace. 
With your schema:

```python
>>> xs = xmlschema.XMLSchema('text.xsd')
>>> xs.types   # global types of you schema
{'root': <XsdComplexType 'root' at 0x7f9e3cbf6eb8>}
>>> len(xs.maps.types)  # all global types of the loaded namespaces 
106
>>> xs.types['root'].content_type[0]    # the first internal element
<XsdElement 'empno' at 0x7f9e3cbf6f98>
>>> xs.types['root'].content_type[0].type   # the first internal element type
<XsdAtomicBuiltin '{http://www.w3.org/2001/XMLSchema}string' at 0x7f9e468f8cf8>
>>> xs.types['root'].content_type[0].type.primitive_type.python_type  # the python type for xs:string 
<class 'str'>
>>> xs.find('/root/empno')    # using XPath for accessing an element
<XsdElement 'empno' at 0x7f9e3cbf6f98>
```

Anyway `xs:string` or `xs:unsignedByte` are not mapped each to a specific Python type, so they share the same basic types. For example:

```python
>>> xs.maps.types['{http://www.w3.org/2001/XMLSchema}unsignedByte'].python_type
<class 'int'>
>>> xs.maps.types['{http://www.w3.org/2001/XMLSchema}int'].python_type
<class 'int'>
```

**Comment by brunato** [comment]
Issue fixed. 
In the new version a schema uses XSD validation modes. For default a schema is built with 'strict' mode, that means it raise an error (parse or validation) when find an error in the schema. You can use also 'lax' mode to build the schema anyway and then check for errors (_all_errors_ schema's property).
