### ISSUE TITLE
Cannot validate multi-level substitution groups?

### ISSUE THREAD

**Issue by iboates** [brunato/xmlschema#93]
I'm new to using this library but I am not sure if I am running into a problem or if I am just doing something wrong, probably the latter though.

I am trying to use [this schema](https://github.com/TatjanaKutzner/CityGML-UtilityNetwork-ADE/blob/master/XSD/CityGML_UtilityNetworkADE.xsd) to validate this XML:

```
<?xml version="1.0" encoding="UTF-8"?>
	<utility:Network gml:id="NetworkID_dccf9248-85ef-11e8-9bfd-7824afca2075"
		xmlns:app="http://www.opengis.net/citygml/appearance/2.0"
		xmlns:luse="http://www.opengis.net/citygml/landuse/2.0"
		xmlns:utility="http://www.citygml.org/ade/utility/0.9.2"
		xmlns:wtr="http://www.opengis.net/citygml/waterbody/2.0"
		xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0"
		xmlns:bldg="http://www.opengis.net/citygml/building/2.0"
		xmlns:core="http://www.opengis.net/citygml/2.0"
		xmlns:smil20="http://www.w3.org/2001/SMIL20/"
		xmlns:grp="http://www.opengis.net/citygml/cityobjectgroup/2.0"
		xmlns:dem="http://www.opengis.net/citygml/relief/2.0"
		xmlns:gen="http://www.opengis.net/citygml/generics/2.0"
		xmlns:tex="http://www.opengis.net/citygml/texturedsurface/2.0"
		xmlns:xlink="http://www.w3.org/1999/xlink"
		xmlns:tun="http://www.opengis.net/citygml/tunnel/2.0"
		xmlns:frn="http://www.opengis.net/citygml/cityfurniture/2.0"
		xmlns:tran="http://www.opengis.net/citygml/transportation/2.0"
		xmlns:gml="http://www.opengis.net/gml"
		xmlns:bridge="http://www.opengis.net/citygml/bridge/2.0"
		xmlns:pbase="http://www.opengis.net/citygml/profiles/base/2.0"
		xmlns:smil20lang="http://www.w3.org/2001/SMIL20/Language"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0"
		xmlns:sch="http://www.ascc.net/xml/schematron">
	<utility:component>
		<utility:ControllerDevice gml:id="ButterflyValveID_ea3d0b42-85ef-11e8-9bfd-7824afca2075">
			<utility:function>shutOff</utility:function>
			<utility:status>inUse</utility:status>
			<utility:locationQuality>unknown</utility:locationQuality>
			<utility:elevationQuality>estimated</utility:elevationQuality>
			<utility:topoGraph xlink:href="#FeatureGraphID_ea3d0b43-85ef-11e8-9bfd-7824afca2075"/>
			<utility:lod1Geometry>
				<gml:Point srsName="EPSG:26910" srsDimension="3">
					<gml:pos>429247.659899995 5444287.21989954 101.053482152581</gml:pos>
				</gml:Point>
			</utility:lod1Geometry>
			<utility:class>valve</utility:class>
		</utility:ControllerDevice>
	</utility:component>
	<utility:component>
		<utility:SimpleFunctionalElement gml:id="SimpleFunctionalElementID_ea3d0b36-85ef-11e8-9bfd-7824afca2075">
			<utility:function>junction</utility:function>
			<utility:status>inUse</utility:status>
			<utility:locationQuality>unknown</utility:locationQuality>
			<utility:elevationQuality>estimated</utility:elevationQuality>
			<utility:topoGraph xlink:href="#FeatureGraphID_ea3d0b37-85ef-11e8-9bfd-7824afca2075"/>
			<utility:lod1Geometry>
				<gml:Point srsName="EPSG:26910" srsDimension="3">
					<gml:pos>430227.849499995 5444806.27949954 57.585048266863</gml:pos>
				</gml:Point>
			</utility:lod1Geometry>
			<utility:class>unknown</utility:class>
		</utility:SimpleFunctionalElement>
	</utility:component>
</utility:Network>
```

This is a rather complex schema so I am feeling a bit over my head, but given this code:

    nanaimo = ET.parse('data/citygml/nanaimo.xml')
    
    my_schema = xmlschema.XMLSchema(r"xsd/CityGML_UtilityNetworkADE.xsd") # .xsd file
    xmlschema.validate(r'data/citygml/nanaimo.xml', my_schema) # xml file

I get an error saying that the `ControllerDevice` tag is an unexpected child of the `contains` tag:

    xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element '{http://www.citygml.org/ade/utility/0.9.2}component' at 0x7f02e5b25e08> with XsdGroup(model='sequence', occurs=[0, 1]):
    Reason: Unexpected child with tag 'utility:ControllerDevice' at position 1.

But this is its (simplified) substitution group hierarchy:

    ABSTRACTNETWORKFEATURE: name="AbstractNetworkFeature" type="utility:AbstractNetworkFeatureType"
        ABSTRACTDEVICE: name="AbstractDevice" substitutionGroup="utility:AbstractNetworkFeature" type="utility:AbstractDeviceType"
            CONTROLLERDEVICE: name="ControllerDevice" substitutionGroup="utility:AbstractDevice" type="utility:ControllerDeviceType"

And for the `Network` element, a relationship is established between `component` and `AbstractNetworkFeature`:

     <element maxOccurs="unbounded" minOccurs="0" name="component" type="utility:AbstractNetworkFeaturePropertyType"/>

And `AbstractNetworkFeaturePropertyType` relates back to the `AbstractNetworkFeature` element via its `ComplexType` tag in the xsd.

I am wondering if maybe this library is not considering the multi-generation inheritance? I am able to validate this file using a different (but proprietary) validator, but I was hoping to implement an open source version.

All of this is in contrast to what happens if you comment out the `<utility:ControllerDevice>` element and its children. It finds the element, only going on to complain about an unexpected <gml:Point> tag, which is next on the list of mysteries for me to solve:

```
xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element '{http://www.citygml.org/ade/utility/0.9.2}lod1Geometry' at 0x7f42a03fc048> with XsdGroup(model='sequence', occurs=[0, 1]):
Reason: Unexpected child with tag 'gml:Point' at position 1.
```

This is (at least to me) an incredibly complex XML schema that spans at least three standards (GML, CityGML, UtilityNetwork ADE), each of which with its own set of namespaces, so I really do appreciate any help you could offer, I feel like I am just not doing something right but I have been at it for days now and I cannot find out why it thinks that the `<utility:ControllerDevice>` is considered "unexpected" when it is related via the substitution groups.

If it helps, there are UML diagrams and an Enterprise Architect file for this data model available here: https://github.com/TatjanaKutzner/CityGML-UtilityNetwork-ADE/tree/master/UML

Thank you

**Comment by brunato** [comment]
Yes, this needs to be fixed. The substitution groups are built correctly but not used properly. This can be fixed adding a recursive method to XsdElement class:

```python
    def iter_substitutes(self):
        for xsd_element in self.maps.substitution_groups.get(self.name, ()):
            yield xsd_element
            for e in xsd_element.iter_substitutes():
                yield e
```
and using this where element check is done (in XsdGroup.iter_decode and XsdGroup.iter_encode).
The fix will be available in the next release.
Thanks

**Comment by brunato** [comment]
The version v1.0.8 is just released.
Best regards

**Comment by zoe-stockholm** [comment]
Hi again @brunato ,

i just found it's our problem in terms of inconsistent schema. Sorry for this. My request close.

**Comment by brunato** [comment]
Okay.
Anyway for release v1.0.11 I'm working for full testing with W3C's XML Schema test suite, also for invalid/inconsistent schema models (UPA violation). Then you will can try your inconsistent schema case with the new release, to check out if the error is recognized at schema instance initialization.
